site_name: Nwangong Community #Docker Tutorial
site_description: Get To Know Nwangong People And Tradition #Getting Started with Docker
site_author: Nwangong Cultural And Development Association (NWACUDA) #Docker
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: asongent/docker-tutorial
repo_url: https://github.com/asongent/docker-tutorial
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021 Docker'

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: red #blue
    accent: red #blue
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: 'images/atem_martin.svg' #'images/docker-labs-logo.svg'

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/asongent/docker-tutorial

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Nwangong History: tutorial/index.md #Getting Started: tutorial/index.md
  - Njilap Community: tutorial/our-application/index.md #Our Application: tutorial/our-application/index.md
  - Lekeng Communtity: tutorial/updating-our-app/index.md #Updating our App: tutorial/updating-our-app/index.md
  - Nwantseng Community: tutorial/sharing-our-app/index.md #Sharing our App: tutorial/sharing-our-app/index.md
  - Ndencup Community: tutorial/persisting-our-data/index.md #Persisting our DB: tutorial/persisting-our-data/index.md
  - Letia Community: tutorial/using-bind-mounts/index.md #Using Bind Mounts: tutorial/using-bind-mounts/index.md
  - Projects: tutorial/multi-container-apps/index.md #Multi-Container Apps: tutorial/multi-container-apps/index.md
  - Social Media Pages: tutorial/using-docker-compose/index.md  #Using Docker Compose: tutorial/using-docker-compose/index.md
  - News Letter: tutorial/image-building-best-practices/index.md #Image Building Best Practices: tutorial/image-building-best-practices/index.md
  - Nwangong Cultural And Development Association: tutorial/what-next/index.md #What Next?: tutorial/what-next/index.md
