name: docker-build
on:
   push:
      branches:
        - 'main'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tracy:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
            




#####Mini
# name: Deploy My Image to My Private Reg

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - "v*-tracy"

# jobs:
#   deploy-docker-hello-world:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}
#           flavor: latest=true
#           tags: |
#             type=ref,event=tag
#             type=ref,event=pr
#             type=semver,pattern={{version}}
#             type=semver,pattern={{major}}.{{minor}}

#       - name: Login to image repository
#         if: github.ref_type == 'tag'
#         uses: docker/login-action@v2
#         with:
#           registry: ${{ secrets.REGISTRY }}
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./Dockerfile
#           push: ${{ github.ref_type == 'tag' }} # ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
      



# ###### --------------------------------
# # name: docker-build
# #   on:
# #     push:
# #       branches:
# #         - 'main'

# #   jobs:
# #     build:
# #       runs-on: ubuntu-latest

# #       steps:
# #         -
# #           name: Checkout 
# #           uses: actions/checkout@v2
# #         -
# #           name: Login to Docker Hub
# #           uses: docker/login-action@v1
# #           with:
# #             username: ${{ secrets.DOCKER_HUB_USERNAME }}
# #             password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
# #         -
# #           name: Set up Docker Buildx
# #           uses: docker/setup-buildx-action@v1
# #         -
# #           name: Build and push
# #           uses: docker/build-push-action@v2
# #           with:
# #             context: .
# #             file: ./Dockerfile
# #             push: true
# #             tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerapp:v01



# #---------------------------------------------


# #Uncomment top to start
# # Ignore This
# # name: Build
# # on: [push, pull_request]
# # jobs:
# #   build:
# #     name: Build
# #     runs-on: ubuntu-latest
# #     steps:
# #     - uses: actions/checkout@v2
# #     - name: Build
# #       uses: docker/build-push-action@v1
# #       with:
# #         push: false
